/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/cp/AppFooter.vue')['default']
    AppMenu: typeof import('./src/components/cp/AppMenu.vue')['default']
    AppSubmenu: typeof import('./src/components/cp/AppSubmenu.vue')['default']
    AppTopbar: typeof import('./src/components/cp/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LandingFooter: typeof import('./src/components/landing/LandingFooter.vue')['default']
    LandingTopbar: typeof import('./src/components/landing/LandingTopbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
